### ISSUE TITLE
cannot find source file 'Parsers.hpp'

### ISSUE THREAD

**Issue by ghost** [ishovkun/phase-field-solid#1]
I am trying to compile your code on a Mac. Deal.II was installed using the provided 8.5 dmg file.

After launching deal.II, and in the folder of your code, typing cmake . resulted in this error

CMake Error at src/lib/CMakeLists.txt:5 (ADD_LIBRARY):
  Cannot find source file:

    Parsers.hpp

Please help. Thanks.

Phu

**Comment by ishovkun** [comment]
Wow, I didn't know someone would try to use this code.
I will update the code.
